### ISSUE TITLE
Prometheus: Network "caddy_internal_net" is declared as external, but could not be found.

### ISSUE THREAD

**Issue by d-rez** [jmb12686/raspi-docker-stacks#18]
Hi there!

Seems like a recent commit cfd4e20094bdff66b4baa2087d13cdf7be327231 breaks prometheus stack deployment

When I try to deploy it I'm getting

`http error: network "caddy_internal_net" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed`

and deployment fails

**Comment by jmb12686** [comment]
@d-rez , I ended up proxying all traffic behind a Caddy reverse proxy.  If you see the `caddy/` directory at the root of this project, that network is defined and created there.  To utilize the latest version of the monitoring stack, you must first deploy the caddy stack.  If you do not wish to utilize caddy for reverse proxy, just use the code from the last commit.

**Comment by sean-ias** [comment]
```docker network create --driver overlay --attachable caddy_internal_net```
